site_name: 'Labs Guides'
site_description: 'Labs guides for Lambda X teams'
site_author: 'Lambda Labs Staff'
site_url: 'https://lambda-school-labs.github.io/labs-guides/'

repo_name: 'Lambda-School-Labs/labs-guides'
repo_url: 'https://github.com/Lambda-School-Labs/labs-guides'

markdown_extensions:
    - tables
    - admonition
    - codehilite:
        linenums: true
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg

plugins:
    - search
    - minify:
        minify_html: true
    - git-committers:
        repository: Lambda-School-Labs/labs-guides
        branch: master
        token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]

theme:
    name: 'material'
    custom_dir: docs/assets/theme/
    favicon: 'assets/images/favicon.png'
    palette:
        primary: 'red'
        accent: 'pink'
    logo:
        icon: 'explore'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
extra_css:
    - 'assets/stylesheets/contributors.css'
extra_javascript:
    - 'assets/javascripts/contributors.js'

extra:
    social:
        - type: 'github'
          link: 'https://github.com/lambda-school-labs'

nav:
    - Home: 'index.md'
    - Git:
        - The Labs workflow: topics/git-workflow-basic.md
        - rebasing a feature branch: topics/git-rebase-feature-branch.md
    - Deployment:
        - Heroku PointDNS: topics/heroku-point-dns.md
        - AWS Amplify Frontend: topics/aws-amplify-deploy.md
        - HTTPS/SSL Support: topics/https-ssl-support.md
    - Writing Standards: topics/writing-standards.md
    