site_name: 'Labs Guides'
site_description: 'Labs guides for Lambda X teams'
repo_name: 'Lambda-School-Labs/labs-guides'
repo_url: 'https://github.com/Lambda-School-Labs/labs-guides'

markdown_extensions:
    - tables
    - admonition
    - codehilite
    - toc:
        permalink: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.details

theme:
    name: 'material'
    favicon: 'img/favicon.png'
    palette:
        primary: 'red'
        accent: 'pink'
    logo:
        icon: 'explore'

extra:
    social:
        - type: 'github'
          link: 'https://github.com/lambda-school-labs'

# nav:
#     - Home: 'index.md'
#     - Writing Standards: topics/writing-standards.md
    