name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      
      - uses: actions/setup-node@master
      - name: Install markdownlint-cli
        run: npm install markdownlint-cli
      - name: Run markdownlint
        run: node_modules/.bin/markdownlint . --config .markdownlint.json --ignore node_modules

      - uses: dschep/install-pipenv-action@v1
      - name: Pipenv install
        run: pipenv install

      - name: Debug install
        run: |
          pipenv run pip list

      - name: Run mkdocs build
        run: pipenv run mkdocs build
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      
      - name: Run mkdocs gh-deploy
        run: pipenv run mkdocs gh-deploy
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  