name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v1

      - name: Run markdownlint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: ".markdownlint.json"

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.10
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
